// import { image } from "./image";
export const dummy = [
  {
    id: 1,
    thumbnail: "http://dummyimage.com/242x100.png/5fa2dd/ffffff",
    // thumbnail: "../src/image/avator.jpg",
    category: "Legal",
    title: "Geologist III",
    desc: "Removal of Traction Apparatus on Left Upper Extremity",
    authorId: 1,
  },
  {
    id: 2,
    thumbnail: "http://dummyimage.com/116x100.png/ff4444/ffffff",
    category: "Business Development",
    title: "Web Developer III",
    desc: "Excision of Left Parietal Bone, Percutaneous Approach",
    authorId: 2,
  },
  {
    id: 3,
    thumbnail: "http://dummyimage.com/178x100.png/cc0000/ffffff",
    category: "Product Management",
    title: "Marketing Manager",
    desc: "Removal of External Fixation Device from Left Lower Femur, External Approach",
    authorId: 3,
  },
  {
    id: 4,
    thumbnail: "http://dummyimage.com/156x100.png/cc0000/ffffff",
    category: "Accounting",
    title: "Analog Circuit Design manager",
    desc: "Transplantation of Left Kidney, Syngeneic, Open Approach",
    authorId: 4,
  },
  {
    id: 5,
    thumbnail: "http://dummyimage.com/215x100.png/cc0000/ffffff",
    category: "Sales",
    title: "Health Coach II",
    desc: "Drainage of Peritoneal Cavity, Percutaneous Endoscopic Approach",
    authorId: 5,
  },
  {
    id: 6,
    thumbnail: "http://dummyimage.com/115x100.png/5fa2dd/ffffff",
    category: "Services",
    title: "Dental Hygienist",
    desc: "Computerized Tomography (CT Scan) of Left Forearm using High Osmolar Contrast",
    authorId: 6,
  },
  {
    id: 7,
    thumbnail: "http://dummyimage.com/245x100.png/dddddd/000000",
    category: "Support",
    title: "Internal Auditor",
    desc: "Bypass Coronary Artery, One Artery from Left Internal Mammary with Zooplastic Tissue, Open Approach",
    authorId: 7,
  },
  {
    id: 8,
    thumbnail: "http://dummyimage.com/103x100.png/5fa2dd/ffffff",
    category: "Human Resources",
    title: "Human Resources Assistant III",
    desc: "High Dose Rate (HDR) Brachytherapy of Peripheral Nerve using Californium 252 (Cf-252)",
    authorId: 8,
  },
  {
    id: 9,
    thumbnail: "http://dummyimage.com/217x100.png/ff4444/ffffff",
    category: "Support",
    title: "Recruiter",
    desc: "Fluoroscopy of Pelvic Arteries using Low Osmolar Contrast, Laser Intraoperative",
    authorId: 9,
  },
  {
    id: 10,
    thumbnail: "http://dummyimage.com/139x100.png/cc0000/ffffff",
    category: "Support",
    title: "Web Designer III",
    desc: "Revision of Drainage Device in Retroperitoneum, External Approach",
    authorId: 10,
  },
];
